tests/mypy/mypy_function_wrapper_fn_t7.py:32: error: Argument 1 to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
tests/mypy/mypy_function_wrapper_fn_t7.py:32: error: Argument 2 to "__call__" of "FunctionWrapper" has incompatible type "str"; expected "Never"  [arg-type]
tests/mypy/mypy_function_wrapper_fn_t7.py:33: error: Argument 1 to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
tests/mypy/mypy_function_wrapper_fn_t7.py:34: error: Argument 1 to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
tests/mypy/mypy_function_wrapper_fn_t7.py:34: error: Argument "y" to "__call__" of "FunctionWrapper" has incompatible type "str"; expected "Never"  [arg-type]
tests/mypy/mypy_function_wrapper_fn_t7.py:76: error: Argument 1 to "__call__" of "BoundFunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
tests/mypy/mypy_function_wrapper_fn_t7.py:76: error: Argument 2 to "__call__" of "BoundFunctionWrapper" has incompatible type "str"; expected "Never"  [arg-type]
tests/mypy/mypy_function_wrapper_fn_t7.py:77: error: Argument 1 to "__call__" of "BoundFunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
tests/mypy/mypy_function_wrapper_fn_t7.py:77: error: Argument 2 to "__call__" of "BoundFunctionWrapper" has incompatible type "str"; expected "Never"  [arg-type]
tests/mypy/mypy_function_wrapper_fn_t7.py:78: error: Argument 1 to "__call__" of "BoundFunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
tests/mypy/mypy_function_wrapper_fn_t7.py:78: error: Argument 2 to "__call__" of "BoundFunctionWrapper" has incompatible type "str"; expected "Never"  [arg-type]
tests/mypy/mypy_function_wrapper_fn_t7.py:80: error: Argument 1 to "__call__" of "BoundFunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
tests/mypy/mypy_function_wrapper_fn_t7.py:80: error: Argument 2 to "__call__" of "BoundFunctionWrapper" has incompatible type "str"; expected "Never"  [arg-type]
tests/mypy/mypy_function_wrapper_fn_t7.py:88: error: Argument 1 to "__call__" of "BoundFunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
tests/mypy/mypy_function_wrapper_fn_t7.py:88: error: Argument 2 to "__call__" of "BoundFunctionWrapper" has incompatible type "str"; expected "Never"  [arg-type]
tests/mypy/mypy_function_wrapper_fn_t7.py:89: error: Argument 1 to "__call__" of "BoundFunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
tests/mypy/mypy_function_wrapper_fn_t7.py:89: error: Argument 2 to "__call__" of "BoundFunctionWrapper" has incompatible type "str"; expected "Never"  [arg-type]
tests/mypy/mypy_function_wrapper_fn_t7.py:185: error: Argument 1 to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
tests/mypy/mypy_function_wrapper_fn_t7.py:185: error: Argument 2 to "__call__" of "FunctionWrapper" has incompatible type "str"; expected "Never"  [arg-type]
tests/mypy/mypy_function_wrapper_fn_t7.py:186: error: Argument 1 to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
tests/mypy/mypy_function_wrapper_fn_t7.py:187: error: Argument 1 to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
tests/mypy/mypy_function_wrapper_fn_t7.py:187: error: Argument "y" to "__call__" of "FunctionWrapper" has incompatible type "str"; expected "Never"  [arg-type]
Found 22 errors in 1 file (checked 1 source file)
