check.py:26: error: Argument 1 to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
check.py:26: error: Argument 2 to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
check.py:34: error: Argument 1 to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
check.py:34: error: Argument 2 to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
check.py:34: error: Argument 3 to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
check.py:34: error: Argument 4 to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
check.py:50: error: Argument 1 to "__call__" of "BoundFunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
check.py:50: error: Argument 2 to "__call__" of "BoundFunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
check.py:51: error: Argument 1 to "__call__" of "BoundFunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
check.py:52: error: Argument 1 to "__call__" of "BoundFunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
check.py:52: error: Argument "b" to "__call__" of "BoundFunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
check.py:54: error: Argument 1 to "__call__" of "BoundFunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
check.py:54: error: Argument 2 to "__call__" of "BoundFunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
check.py:57: error: Argument 1 to "__call__" of "FunctionDecorator" has incompatible type "type[Two]"; expected "Callable[[VarArg(Never), KwArg(Never)], Never] | Callable[[type[Never], VarArg(Never), KwArg(Never)], Never] | Callable[[type[Never]], Never] | Descriptor"  [arg-type]
check.py:71: error: Argument 1 to "__call__" of "BoundFunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
check.py:71: error: Argument 2 to "__call__" of "BoundFunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
check.py:73: error: Argument 1 to "__call__" of "BoundFunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
check.py:73: error: Argument 2 to "__call__" of "BoundFunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
check.py:76: error: Missing return statement  [empty-body]
check.py:142: error: Argument 1 to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
check.py:142: error: Argument 2 to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
check.py:150: error: Argument 1 to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
check.py:150: error: Argument 2 to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
check.py:158: error: Argument 1 to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
check.py:158: error: Argument 2 to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
tests/mypy/mypy_decorator_t1.py:33: error: Incompatible types in assignment (expression has type "int", variable has type "str")  [assignment]
tests/mypy/mypy_decorator_t1.py:36: error: Too few arguments for "__call__" of "FunctionWrapper"  [call-arg]
tests/mypy/mypy_decorator_t1.py:41: error: Argument 1 to "__call__" of "FunctionWrapper" has incompatible type "str"; expected "int"  [arg-type]
tests/mypy/mypy_decorator_t1.py:44: error: Too many arguments for "__call__" of "FunctionWrapper"  [call-arg]
tests/mypy/mypy_decorator_t1.py:64: error: Too few arguments for "__call__" of "FunctionWrapper"  [call-arg]
tests/mypy/mypy_decorator_t1.py:69: error: Argument 1 to "__call__" of "FunctionWrapper" has incompatible type "str"; expected "int"  [arg-type]
tests/mypy/mypy_decorator_t1.py:72: error: Too many arguments for "__call__" of "FunctionWrapper"  [call-arg]
tests/mypy/mypy_decorator_t1.py:101: error: Incompatible types in assignment (expression has type "str", variable has type "int")  [assignment]
tests/mypy/mypy_decorator_t1.py:104: error: Too few arguments for "function3"  [call-arg]
tests/mypy/mypy_decorator_t1.py:109: error: Argument 1 to "function3" has incompatible type "str"; expected "int"  [arg-type]
tests/mypy/mypy_decorator_t1.py:112: error: Too many arguments for "function3"  [call-arg]
tests/mypy/mypy_decorator_t1.py:137: error: Too few arguments for "__call__" of "FunctionWrapper"  [call-arg]
tests/mypy/mypy_decorator_t1.py:142: error: Argument 1 to "__call__" of "FunctionWrapper" has incompatible type "str"; expected "int"  [arg-type]
tests/mypy/mypy_decorator_t1.py:145: error: Too many arguments for "__call__" of "FunctionWrapper"  [call-arg]
tests/mypy/mypy_decorator_t1.py:220: error: Argument 1 to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
tests/mypy/mypy_decorator_t1.py:220: error: Argument 2 to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
tests/mypy/mypy_decorator_t1.py:222: error: Argument 1 to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
tests/mypy/mypy_decorator_t1.py:223: error: Argument 1 to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
tests/mypy/mypy_decorator_t1.py:223: error: Argument "b" to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
tests/mypy/mypy_decorator_t1.py:231: error: Argument 1 to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
tests/mypy/mypy_decorator_t1.py:231: error: Argument 2 to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
tests/mypy/mypy_decorator_t1.py:233: error: Argument 1 to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
tests/mypy/mypy_decorator_t1.py:234: error: Argument 1 to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
tests/mypy/mypy_decorator_t1.py:234: error: Argument "b" to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
tests/mypy/mypy_decorator_t1.py:242: error: Argument 1 to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
tests/mypy/mypy_decorator_t1.py:242: error: Argument 2 to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
tests/mypy/mypy_decorator_t1.py:244: error: Argument 1 to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
tests/mypy/mypy_decorator_t1.py:245: error: Argument 1 to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
tests/mypy/mypy_decorator_t1.py:245: error: Argument "b" to "__call__" of "FunctionWrapper" has incompatible type "int"; expected "Never"  [arg-type]
Found 54 errors in 2 files (checked 1 source file)
